name: Jayson Rivest
favicon: null
layout_spectrum: 1
typography_spectrum: 0.32143
title: Jayson Rivest
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#256083'
    - '#000000'
    - '#004080'
    - '#225577'
    - '#006666'
  brandStrength: 0.375
  lightness: 0.375
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
