name: Jayson Rivest
favicon: null
layout_spectrum: 0.6093209597747773
typography_spectrum: 0.7519998555071652
title: Jayson Rivest
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.20789426076225936
  lightness: 0.27851840970106423
  saturation: 0.4827004650142044
  rhythmicContrast: 0.7231676569208503
purpose: []
