typography_spectrum: 0.32143
color:
  brandColors:
    - '#002b4d'
    - '#02021c'
    - '#001937'
    - '#024573'
    - '#10649f'
  brandStrength: 0.375
  lightness: 1
  saturation: 0.375
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Jayson Rivest
  email: jayson@jaysonrivest.com
  url: www.jaysonrivest.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/94c8eb78-3524-4823-8648-285551d0f740.png
name: Jayson Rivest
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Welcome
    id: d9007008-9723-48ee-91b9-5180f618a598
    type: content
favicon: null
title: Jayson Rivest
purpose: []
