name: Jayson Rivest
favicon: null
layout_spectrum: 1
typography_spectrum: 0.07629
title: Jayson Rivest
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d6ebff'
    - '#173501'
    - '#b5ee3d'
    - '#8fbbaa'
    - '#5e9053'
  brandStrength: 0.375
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
